<?php

function follow_habrapack_follow_icon_styles_alter(&$styles) {

  $css = array(
    'height: 32px;',
    'line-height: 32px;',
    'padding-left: 40px;',
    'margin-top: .3em',
  );

  $path_to_me = drupal_get_path('module', 'follow_habrapack');

  $styles['follow-habrapack-with-shadow'] = array(
    'name' => 'follow-habrapack-with-shadow',
    'label' => t('HabraPack with shadow'),
    'css-overrides' => $css,
    'icon-path' => "${path_to_me}/icons/with-shadow",
  );

  $styles['follow-habrapack-without-shadow'] = array(
    'name' => 'follow-habrapack-without-shadow',
    'label' => t('HabraPack without shadow'),
    'css-overrides' => $css,
    'icon-path' => "${path_to_me}/icons/without-shadow",
  );

}

function follow_habrapack_follow_networks_alter(&$networks, $uid = 0) {
  //dpm($uid);
  $items = array(
    'bliptv',
    'delicious',
    'flickr',
    'lastfm',
    'myspace',
    'picasa',
    'spiceworks',
    'viadeo',
    'virb',
    'xing',
  );
  foreach($items as $item) {
    unset($networks[$uid][$item]);
  }
}
